Database time
sunmoyed/growus pull request #18
Opened 2018-07-03 21:03 UTC by meimeisuns

database linking complete

2018-07-06 07:34 UTC, daiyi requested changes
Exciting progress :D One thing though, I think you might have initialised your db locally manually in the command line, but not in the server code. So when I go to run the server, there isn't a db :'D Can you add the initialisation?

2018-07-06 08:50 UTC, daiyi commented
Ohh I see, you committed your database into the code. I think it's best if we only keep code in this repository, and leave things like local test databases on our own computers. For a couple reasons:

1. We want to keep the project clean, and I imagine having it full of test data will be messy. We will both have our private local test databases full of foobars and fake exercises \o/
2. The code shouldn't assume any database state. Anyone should be able to clone the project anew and go through the instructions and get a working app. When the app gets booted for the first time, it should notice it doesn't have a db, and initialise one.

2018-07-06 18:20 UTC, meimeisuns commented
deleted the database and pushed the endpoints I mentioned xD I'll figure out how to make it initialize the db (probably just through makefile?) and then I think we good to merge

2018-07-06 18:35 UTC, daiyi commented
If possible, it might be best to initialise the db through the server (`growus.py`?) somehow!

2018-07-06 18:43 UTC, meimeisuns commented
yeah I don't know how to do that since the tutorial I used says we need to run sqlite on the command line to make it create the db from the schema, but I'll look into it 

I think the flaskr tutorial has what we're going for, but the way they run and programmed their app seems more fundamentally different from ours is now, so we might have to do a complete overhaul to use their approach

2018-07-08 06:48 UTC, daiyi requested changes
it's looking good \o///

2018-07-08 06:48 UTC, daiyi commented on growus/growus.py
> +	models.insert_exercise(exercise_type, user_id, name, description)
When you create a new row in the db, there's some new information, such as `id`. Perhaps you can have `insert_exercise` return the new row? It's possible that `cursor.execute` already does this.

2018-07-08 06:48 UTC, daiyi commented on growus/growus.py
> +	user_id = request.form['userId']
Can you change it to expect a json response rather than form input? also the other endpoints (:

2018-07-08 06:48 UTC, daiyi commented on growus/growus.py
> +@app.route("/exercises/all", methods = ["GET"])
We talked about a new api design, lets update these endpoints!

2019-09-16 05:11 UTC, daiyi commented
Closing due to #24

2019-09-16 05:11 UTC, closed without merging